Add multiValueHeaders field to API Gateway event.
lifeomic/alpha pull request #119
Opened 2022-01-29 00:12 UTC by david-wb

This adds one more thing to make `alpha.post(handler)` requests work with `apollo-server-lambda` v3 handlers.

2022-01-31 14:31 UTC, jagoda requested changes

2022-01-31 14:31 UTC, jagoda commented on src/adapters/helpers/lambdaEvent.js
> +      'Content-Type': 'application/json'
This looks like it assumes that all requests will contain JSON payloads. I would expect that to cause problems in some cases. Could we process `config.headers` to generate the values here?

2022-01-31 16:06 UTC, david-wb commented on src/adapters/helpers/lambdaEvent.js
> +      'Content-Type': 'application/json'
@jagoda Good point. I made it so  it now copies the content-type header into `multiValueHeaders` if it exists. How's that?

2022-01-31 16:24 UTC, jagoda commented on src/adapters/helpers/lambdaEvent.js
> +      'Content-Type': 'application/json'
I think this is the right idea! However, best I can tell, the schema for `multiValueHeaders` is an array per key that collects the values (rather than a single value). See https://github.com/awsdocs/aws-lambda-developer-guide/blob/main/sample-apps/nodejs-apig/event.json#L22

2022-01-31 16:24 UTC, jagoda commented on src/adapters/helpers/lambdaEvent.js
> +    if (name.toLocaleLowerCase() === 'content-type') {
Selecting the single header seems fine for our current purposes, but I wonder if it would be worthwhile to go ahead and record all headers here.

2022-01-31 16:41 UTC, david-wb commented on src/adapters/helpers/lambdaEvent.js
> +    if (name.toLocaleLowerCase() === 'content-type') {
Sure we can try that.

2022-01-31 17:00 UTC, david-wb commented on src/adapters/helpers/lambdaEvent.js
> +      'Content-Type': 'application/json'
Done.

2022-01-31 17:09 UTC, david-wb commented
@jagoda The preRelease check keeps failing. Not sure why.

2022-01-31 21:06 UTC, jagoda commented
> @jagoda The preRelease check keeps failing. Not sure why.

> 403 403 Forbidden - PUT https://registry.npmjs.org/@lifeomic%2falpha - You may not perform that action with these credentials.

I think this is probably related to the NPM security work that @smolster and others have been working on. My understanding is that we should remove the pre-release action in light of that work.

2022-01-31 21:47 UTC, david-wb commented on .github/workflows/pr-branch-build.yaml
> -  preRelease:
@jagoda I removed the preRelease job here, hopefully that's what you meant.

2022-01-31 21:52 UTC, smolster commented on .github/workflows/pr-branch-build.yaml
> -  preRelease:
This is the right change -- my automation mistakenly didn't detect this repo's pre-release step.

Thanks for fixing @david-wb!

2022-02-02 00:14 UTC, david-wb commented
@jagoda Is this good to go? My unit tests in another project depend on it, but I can work around it if you think this might cause other issues.

2022-02-02 13:40 UTC, jagoda approved these changes

2022-02-02 13:40 UTC, jagoda commented on src/adapters/helpers/lambdaEvent.js
> +      const values = value.split(',').map((v) => v.trim());
It's unclear to me if splitting on commas here is always safe. For example, we use some proprietary headers that are JSON strings. Splitting these values on comma would result in invalid JSON fragments. However, I'm not sure how else to do this without enumerating all headers that should be split so maybe this is OK.

2022-02-02 13:41 UTC, jagoda commented
I'm sorry @david-wb I got sidetracked yesterday. I think this is good to go. Thanks!

2022-02-02 15:11 UTC, merged